# Generated by Django 4.1.2 on 2022-11-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nut',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
